ДЗ 2
EvilMurlok/2022-2-VK-EDU-FS-Frontend-I-Panin pull request #2
Opened 2022-10-11 11:07 UTC by EvilMurlok

# Домашнее задание № 2 #

Прошу @martinkomitsky или @HaseProgram проверить его.

Что было сделано: 
* за образец брался _web-telegram_;
* было принято решение сразу заготовить определенную структуру проекта и все разбивать на компоненты;
* разработана архитектура приложения. Корневая папка _src_. В ней находится непосредственно точка входа _index.html_ и _index.js_. В поддиректории _app_ находятся все компоненты, начиная от весомых (находятся в _components_) и заканчивая маленькими элементами, которые могут повторяться на страницах (находятся в _ui_). Вся статика: будь то шрифты (решил использовать _RockStar regular_, ибо очень нравится, надеюсь, не возбраняется:-)), фотографии и иконки _.svg_, ну и стили ко всем компонентам и страницам лежат в поддиректории _sass_;
* в соответсвии со структурой был изменен _webpack.config.js_;
* было принято решение сразу использовать препроцессор _sass_, ибо он позволяет использовать константы (которые крайне пригодятся при адаптивной верстке), лучше верстать согласно технологии _bem_, да и просто уже очень к нему привык и намного проще с ним. Пожалуйста, не снимайте баллы;   
* была разработана система отправки писем (пока что без анимаций вообще, думаю, что в 3 домашке все прикручу, чтобы было красиво:-)). Оставлены комментарии в коде;
* особо хочу отметить, что была убрана форма и задействован просто _div_ в поле ввода сообщения. Сделано это для того, чтобы и не использовать дурацкий _textarea_, и позволить пользователю набирать текст в много строк (простой _input_ такого не позволяет), там все в строку:-(. Из-за этого теперь не работает _enter_ (он просто переносит на новую строку). Отправка только по клику на кнопку. Проверил, в веб-телеграмме аналогичная механика.

2022-10-13 00:42 UTC, HaseProgram requested changes
Привет! Вижу, что работа проделана прям классная (вебкомпонеты и даже вебпак 😮), но добавь еще, пожалуйста, деплой на github-pages. Если что, инструкция есть в описание ДЗ.

Заодно предлагаю все-таки воскресить отправку сообщений по кнопке) Чтобы не конфликтовало с переносом строки, попробуй сделать отправку через Ctrl+Enter :)

2022-10-13 11:33 UTC, EvilMurlok commented
@HaseProgram, прошу прощения за беспокойство, я вроде настроил деплой, добавил файлик требуемый, даже прошли все этапы деплоя (есть раздел checks, где все пройдено, галочки стоят). И как я понял, оно автоматически заливает на pages. Или надо проделать еще какие-то действия?

2022-10-13 12:19 UTC, martinkomitsky commented
> @HaseProgram, прошу прощения за беспокойство, я вроде настроил деплой, добавил файлик требуемый, даже прошли все этапы деплоя (есть раздел checks, где все пройдено, галочки стоят). И как я понял, оно автоматически заливает на pages. Или надо проделать еще какие-то действия?

Вижу, что некий деплой имеется, но там не работает
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/14847018/195594298-26789b67-18fa-4c2c-9fc7-e791f0f58115.png">

2022-10-13 17:32 UTC, EvilMurlok commented
@HaseProgram @martinkomitsky, прошу прощения за свою тупость, забыл импорты указать, поэтому webpack эти файлы и не насобирал нигде:( 
Добавил  возможность отправки сообщений по ctrl+enter, однако там можно гибко настроить любое сочетание клавиш благодаря хелперу. 
Ссылку на развернутую штуку прилагаю для удобства: https://evilmurlok.github.io/2022-2-VK-EDU-FS-Frontend-I-Panin/

Жаль, что код нельзя менять, но я в комментариях там отметил, что если изменить логин пользователя и компаньона в диалоге, то можно увидеть диалог "с другой стороны": появятся уже две галочки (прочитано) вместо одной, и сообщения поменяют свое горизонтальное расположение.

2022-10-14 09:00 UTC, EvilMurlok commented
@HaseProgram, добрый день. Если теперь все верно и замечаний нет, не могли бы Вы закрыть мерж-реквест, пожалуйста🙏🏻 Хочется к 3 и 4 дз приступать😅

2022-10-14 11:41 UTC, HaseProgram commented
> @HaseProgram, добрый день. Если теперь все верно и замечаний нет, не могли бы Вы закрыть мерж-реквест, пожалуйста🙏🏻 Хочется к 3 и 4 дз приступать😅

Привет! Да, все отлично, работа супер, 12

2022-10-14 11:41 UTC, HaseProgram approved these changes

2022-10-14 11:41 UTC, merged

2022-10-15 07:37 UTC, martinkomitsky commented
> Хочется к 3 и 4 дз приступать

Как я говорил раньше, работа над ошибками над текущим ДЗ не должно останавливать от работы над следующими ДЗ. Просто открывай новые ветки и делай в них, иначе сроки будут поджимать все сильнее и сильнее